### ISSUE TITLE
TypeError: get() got an unexpected keyword argument 'fallback'

### ISSUE THREAD

**Issue by techraf** [mikeSimos/vsphere_ansible_inventory#2]
Most likely only on Python 2.x the inventory script fails with:

```
$ ansible all -i vsphere_inventory.py -m ping
ERROR! Attempted to execute "vsphere_inventory.py" as inventory script: Inventory script (vsphere_inventory.py) had an execution error: Traceback (most recent call last):
  File "/home/macraf/ansible-vmware-inventory/vsphere_ansible_inventory/vsphere_inventory.py", line 297, in <module>
    main()
  File "/home/macraf/ansible-vmware-inventory/vsphere_ansible_inventory/vsphere_inventory.py", line 267, in main
    = parse_config()
  File "/home/macraf/ansible-vmware-inventory/vsphere_ansible_inventory/vsphere_inventory.py", line 223, in parse_config
    cache_path = config.get('GENERIC', 'cache_path', fallback='/tmp/ansible-vsphere-inventory-cache.tmp')
TypeError: get() got an unexpected keyword argument 'fallback'
```

**Comment by sorpa** [comment]
I am getting exactly the same error message. Trying to run this against vcenter version 6.

**Comment by mikesimos** [comment]
This is an issue with python 2/3 cross compatibility on the script. I will give it some time later on today.
Thank you both!

**Comment by sorpa** [comment]
Hi,

Thanks for fix. Even though it was still giving error message when running
it:

ansible@ansible ansible-playbooks/inventory$ ansible all -i
vsphere_inventory.py -m ping
ERROR! Attempted to execute "vsphere_inventory.py" as inventory script:
Inventory script (vsphere_inventory.py) had an execution error:

I tried several ways and realized that the certificate check was not
working? Even I had the *vsphere_cert_check = False *in ini-file.

I added the following lines to the .py script and then it started to work:







*import ssltry:   _create_unverified_https_context =
ssl._create_unverified_contextexcept AttributeError:   passelse:
ssl._create_default_https_context = _create_unverified_https_context*

ansible@ansible ansible-playbooks/inventory$ ansible all -i
vsphere_inventory.py -m ping

10.81.2.100 | SUCCESS => {
    "changed": false,
    "ping": "pong"
}

Maybe this needs to be like that when running against vsphere 6 vcenter?

Thanks,
Pasi

**Comment by mikesimos** [comment]
Thanks Pasi,
Should be fine after last commits refactoring of cert_check logic. Much simpler and straightforward now.
Best Regards!
